name: Update Market Crystal Data

on:
  schedule:
    - cron: '0 9 * * *' # 日本時間 18:00
  workflow_dispatch: # 手動実行用

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # v2からv4に更新

      - name: Set up Python
        uses: actions/setup-python@v5 # v2からv5に更新
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install yfinance pandas scikit-learn torch lxml Beautifulsoup4

      - name: Run update script
        # ファイルがトップ階層にある場合は scripts/ を消して python generate_json.py にしてください
        run: python generate_json.py 

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add crystal_4d.json
          git commit -m "Auto-update crystal data" || exit 0
          git push
